spring:
  application:
    name: wealthcheck
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000
  cookie:
    name: "wc-token"
    max-age: 3600
    secure: true

google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://wealthcheck.duckdns.org/api/v1/auth/callback

app:
  frontend:
    url: https://wealthcheck.duckdns.org

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
